[build]
publish = "public"
command = "npm install -g autoprefixer postcss postcss-cli && hugo --gc --minify --buildDrafts=false"

[context.deploy-preview.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENABLEGITINFO = "true"