[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "Javascript"
  url = "/posts/"
  weight = 20

[[main]]
  name = "Python"
  url = "/test/"
  weight = 20

[[main]]
  name = "Other Artcles"
  url = "/notes/"
  weight = 30

[[main]]
  name = "Author"
  url = "/about/"
  weight = 40

[[main]]
  name = "Links"
  url = "/links/"
  identifier = "Links"
  weight = 45

[[main]]
  name = "Github"
  url = "https://github.com/mwongeraE"
  parent = "Links"
  weight = 10

[[main]]
  name = "<img src=\"/icons/mail.svg\" style=\"height:1.2rem; display: inline; margin: 5px;\"> Contact"
  url = "/contact/"
  weight = 50

[[main]]
  name = "<img src=\"/icons/search.svg\" style=\"height:1.2rem; display: inline; margin: 5px;\"> Search"
  url = "/search/"
  weight = 60